- src/tracking.js
> XW-3972 | Do not trigger custom dimensions if method does not exist

- README.md
- src/index.html
- src/index.js
Description:
This modifications are to implement the Autostart: viewable option on the jwplayer library in order to have the possibility to see the videos automatically on play when the user can see 60% of the video in the screen
Evidences:
https://user-images.githubusercontent.com/25180798/115432146-ab577280-a1cb-11eb-98fc-da6afa0b19e1.mov
> Autostart viewable option

- src/index.js
@unijuglr 
Support proper jw player configuration
> Enable vpaid ads

- .eslintignore
- package.json
- rollup.config.js
- src/main.ts
- src/players/shared/JwPlayerWrapper.tsx
- src/players/shared/addBaseTrackingEvents.ts
- src/types.d.ts
- src/utils/getVideoPlayerVersion.ts
- src/utils/globalJWInterface.ts
- src/utils/videoTracking.ts
- src/utils/videoTrackingGlobalProps.ts
- yarn.lock
* Upgrade tracking library to add `debug` and `env` params automatically. 
* Change tracker factory to one that doesn't add category prefixes
> DPAD-262 | More video tracking events and fixes

- src/plugins/fandom-wirewax.plugin.ts
Update WW events with the event names and data provided in the spreadsheet.
> DPAD-34 | WireWax event updates

- JenkinsFile
- package.json
- src/utils/globalJWInterface.ts
- src/utils/videoTracking.ts
- src/utils/videoTrackingGlobalProps.ts
- yarn.lock
* Use the tracking library to send the events to DW
* Remove some code that is now handled in the library now
> Update tracking with library updates

- package.json
- src/utils/videoTimingEvents.ts
- yarn.lock
* Update to the new version of tracking library that supports custom sampling
* Increase custom sampling
> Update recording library 

- src/players/DesktopArticleVideoPlayer/DesktopArticleVideoPlayer.tsx
https://fandom.atlassian.net/browse/DPAD-3
> DPAD-3: Mini-player is overlapped by page tooltip

- package.json
- src/players/CanonicalVideoPlayer/CanonicalVideoPlayer.tsx
- src/players/shared/JwPlayerWrapper.tsx
- src/players/shared/LoadableVideoPlayerWrapper.tsx
- src/types.d.ts
- src/utils/slugify.ts
- test-jw/src/App.js
- test-jw/src/videoConfigs.js
https://fandom.atlassian.net/browse/DPAD-749
> DPAD-749: [mobile] make player "sticky" as you scroll on canonical pages

- package.json
- src/players/shared/JwPlayerWrapper.tsx
- src/types.d.ts
- src/utils/slugify.ts
https://fandom.atlassian.net/browse/DPAD-386
> DPAD-386: Enable "sharing" from video embeds to the canonical page

- package-lock.json
- package.json
- src/loaders/CanonicalVideoLoader.tsx
- yarn.lock
[DPAD-1085 :: Video player doesn't refresh after clicking on a different video](https://fandom.atlassian.net/browse/DPAD-1085)
When I click on a video from “Videos you might like”, the player still plays the same video. New video appears only after I refresh the page.
Fixed this behavior caused by the lazy loader ignoring props change on SPAs
[FAT Deployment](https://build-dpad-1085.apps.fandom-dev.us/video/)
> DPAD-1085 :: Fix canonical player not reloading properly

- src/jwplayer/players/shared/addBaseTrackingEvents.ts
~(pending verification we want this from Nick)~ done
* Changes the content_start event to fire after every new video play
> Fire content start every video

- package.json
- src/jwplayer/players/shared/JwPlayerWrapper.tsx
- src/loaders/DesktopArticleVideoLoader.tsx
Directly import the player in the Desktop Video Loader
> DPAD-1175 :: Directly import the player in the Desktop Video Loader and get rid of auto pause after 4th+ play

- package.json
- src/jwplayer/players/DesktopArticleVideoPlayer/DesktopArticleVideoPlayer.tsx
- src/jwplayer/players/MobileArticleVideoPlayer/MobileArticleVideoPlayer.tsx
- src/jwplayer/players/shared/JwPlayerWrapper.tsx
Turn off stopAutoAdvance feature for the Desktop and Mobile wiki players
> DPAD-1339 :: Turn off stopAutoAdvance feature for the Desktop and Mobile wiki players

- package.json
- src/jwplayer/players/MobileArticleVideoPlayer/OffScreenOverlay/OffScreenOverlay.tsx
https://fandom.atlassian.net/browse/DPAD-1377
> DPAD-1377: Ads on JWP on mobile do not have player buttons

- package.json
- src/jwplayer/players/RedVentureVideoPlayer/RedVentureVideoPlayer.tsx
- src/jwplayer/utils/videoTimingEvents.ts
- yarn.lock
* https://fandom.atlassian.net/browse/DPAD-1457
Update browser tracking library so that beaconId is sourced properly on N&R sites
> DPAD-1457 :: Update browser tracking library

- package.json
- src/jwplayer/players/DesktopArticleVideoPlayer/UnmuteButton.tsx
https://fandom.atlassian.net/browse/DPAD-1454
> DPAD-1454: 'Play sound' button does not disappear after unmuting video

- src/jwplayer/players/RedVentureVideoPlayer/RedVentureVideoPlayer.tsx
- src/jwplayer/players/RedVentureVideoPlayer/getRedVentureVideoConfig.ts
- src/jwplayer/types.d.ts
- stand-alone/loaderHelper.ts
- stand-alone/standalone-loader.tsx
Add in an autoPlay override param to the loadPlayer function which will take precedence over the usual autoPlay checks in the redVentureVideoConfig file
> DPAD-1491 :: Add in an autoPlay override param to the loadPlayer function

- stand-alone/README.md
Updated the README.md for the stand-alone player to reflect app structure changes and how the player is imported there
> VIDEO-447 :: Updated the README.md 

- README.md
video-448 :: Updated the main README.md on how to do local development of the Fandom JWPlayer | Documented the Youtube Takeover Player | Documented package deployment | Documented and briefly talked about loaders
> video-448 :: updated docs

- src/jwplayer/players/DesktopArticleVideoPlayer/DesktopArticleVideoPlayer.tsx
- src/jwplayer/players/MobileArticleVideoPlayer/MobileArticleVideoPlayer.tsx
- src/jwplayer/players/shared/JwPlayerWrapper.tsx
- src/jwplayer/types.d.ts
- src/jwplayer/utils/utils.ts
https://fandom.atlassian.net/browse/VIDEO-183
--------------
Draft PR for localhost testing --> https://github.com/Wikia/jwplayer-fandom/pull/169
> VIDEO-183 - When mini-player is closed, continue playing pre-roll ad until completion off-screen

- src/jwplayer/utils/articleVideo/articleVideoConfig.ts
- src/types/index.d.ts
https://fandom.atlassian.net/browse/VIDEO-603
------------
This way we can use Optimizely to provide an alternative playlist through setting the `window.videoExperiments.playlistUrl` variable.
Example playlist url: https://cdn.jwplayer.com/v2/media/dWVV3F7S
> Allow passing an alternative playlist in a form of a url

- package.json
- src/jwplayer/players/MobileArticleVideoPlayer/mobileArticleVideoPlayer.module.scss
- stand-alone/yarn.lock
[ticket](https://fandom.atlassian.net/browse/COTECH-710)
Description:
Brackets were placed wrong and that causes an issue with More button that have bigger z-index and covers the video.
> COTECH-710 (fix): fix zindex issue on mobile

- src/jwplayer/players/shared/addBaseTrackingEvents.ts
- src/jwplayer/utils/utils.ts
https://fandom.atlassian.net/browse/COTECH-664
> Add 'video_ad_is_in_gallery' tracking param

- stand-alone/standalone-loader.tsx
https://fandom.atlassian.net/browse/COTECH-623
> COTECH-623 Extend fandomContext when JWP is loaded by loadPlayer()

- JenkinsFile
- package.json
- src/loaders/utils/GetMediaWikiConfigDetails.ts
- yarn.lock
https://fandom.atlassian.net/browse/COTECH-711
> COTECH-711 | Typescript check

- src/loaders/DesktopArticleVideoLoader.tsx
- src/loaders/MobileArticleVideoLoader.tsx
- src/loaders/utils/tracking.ts
- test-jw/yarn.lock
https://fandom.atlassian.net/browse/COTECH-808
> COTECH-808 | eligible event

- src/jwplayer/players/RedVentureVideoPlayer/RedVentureVideoPlayer.tsx
- src/jwplayer/types.d.ts
- stand-alone/loaderHelper.ts
- stand-alone/standalone-loader.tsx
- stand-alone/types.d.ts
https://fandom.atlassian.net/browse/COTECH-581
> COTECH-581 | Use hasAds in standalone player

- src/jwplayer/players/DesktopArticleVideoPlayer/DesktopArticleVideoPlayer.tsx
- src/jwplayer/players/MobileArticleVideoPlayer/MobileArticleVideoPlayer.tsx
- src/jwplayer/players/RedVentureVideoPlayer/RedVentureVideoPlayer.tsx
- src/jwplayer/players/shared/JwPlayerWrapper.tsx
- src/jwplayer/players/shared/LoadableVideoPlayerWrapper.tsx
- src/jwplayer/types.d.ts
https://fandom.atlassian.net/browse/COTECH-970
> COTECH-970 | Disable auto-advance for ROW countries

- src/jwplayer/players/shared/JwPlayerWrapper.tsx
- src/jwplayer/players/shared/JwPlayerWrapperWithStrategyRules.tsx
- src/jwplayer/types.d.ts
- src/jwplayer/utils/articleVideo/articleVideoConfig.ts
> COTECH-1074 Pass playlist ID to JWP:SR using key-value pairs

- src/jwplayer/players/DesktopArticleVideoPlayer/DesktopArticleVideoPlayer.tsx
- src/jwplayer/players/MobileArticleVideoPlayer/MobileArticleVideoPlayer.tsx
- src/loaders/types.d.ts
https://fandom.atlassian.net/browse/COTECH-1007
> COTECH-1007 | prevent rendering if canPlayVideo returns false

- src/jwplayer/players/CanonicalVideoPlayer/canonicalOnReady.ts
- src/jwplayer/players/MobileArticleVideoPlayer/MobileArticleVideoPlayer.tsx
- src/jwplayer/players/RedVentureVideoPlayer/redVenturePlayerOnReady.ts
- src/jwplayer/players/shared/JwPlayerWrapper.tsx
- src/jwplayer/players/shared/JwPlayerWrapperWithStrategyRules.tsx
- src/jwplayer/players/shared/addBaseTrackingEvents.ts
- src/jwplayer/utils/articleVideo/articlePlayerOnReady.ts
- src/jwplayer/utils/useAdEngineComplete.ts
- src/jwplayer/utils/useBeforeJwpWrapperRendered.ts
- src/jwplayer/utils/useJwpAdsSetupComplete.ts
- src/jwplayer/utils/useRvAdComplete.ts
- src/jwplayer/utils/videoTimingEvents.ts
- src/jwplayer/utils/videoTracking.ts
- test-jw/src/index.jsx
https://fandom.atlassian.net/browse/COTECH-1026
* added new timing events
* removed unneeded timing events
> COTECH-1026 | tracking performance events

- src/jwplayer/players/shared/JwPlayerWrapper.tsx
https://fandom.atlassian.net/browse/COTECH-1142
> COTECH-1142 | Fix sponsored content country codes (UK => GB, AUS => AU)

- src/loaders/CanonicalVideoLoader.tsx
- src/loaders/DesktopArticleVideoLoader.tsx
- src/loaders/MobileArticleVideoLoader.tsx
- src/loaders/utils/tracking.ts
https://fandom.atlassian.net/browse/COTECH-1025
> COTECH-1025 Add video player details to eligible event payload

- src/jwplayer/players/shared/CloseButton/CloseButton.tsx
Related to changes in the AdEngine: https://github.com/Wikia/ad-engine/pull/2461.
> COTECH-1164 Add new event to JWP on close button clicked

- src/jwplayer/players/shared/JWEvents.ts
- src/jwplayer/players/shared/JwPlayerWrapperWithStrategyRules.tsx
https://fandom.atlassian.net/browse/COTECH-1160
> COTECH-1160 | unset player on remove, placement search param

- src/jwplayer/players/shared/JwPlayerWrapperWithStrategyRules.tsx
- src/jwplayer/players/shared/StrategyRulesWrapper.tsx
- test-jw/src/App.jsx
- test-jw/src/adEngineMock.js
- test-jw/src/videoConfigs.js
https://fandom.atlassian.net/browse/COTECH-1206
> COTECH-1206 | pass vastXml to JWP:SR
