Wikia/jwplayer-fandom

src/players/shared/addBaseTrackingEvents.ts, src/types.d.ts, src/utils/globalJWInterface.ts, src/utils/videoTracking.ts, src/utils/videoTrackingGlobalProps.ts
* Fires events for ads at one second intervals for first ten seconds then one per ten seconds
* Fires event for content at 10 seconds intervals until the first minute than at one minute intervals
=> DPAD-34 | Add heartbeat tracking

package.json, src/utils/articleVideo/articlePlayerOnReady.ts, src/utils/useAdComplete.ts, src/utils/videoTimingEvents.ts
https://fandom.atlassian.net/browse/DPAD-391
New timing events present:
'jw-player-ad-eng-opt-in-listen-start'
'jw-player-ad-eng-opt-in-message-recieved'
'jw-player-ad-eng-config-listen-start'
'jw-player-ad-eng-config-message-recieved'
'jw-player-ad-eng-setup-jw-listen-start'
'jw-player-ad-eng-setup-jw-message-recieved'
'jw-player-ad-eng-player-ready-dispatch'
=> Adding timings for DPAD-391

package.json, src/jwplayer/players/DesktopArticleVideoPlayer/DesktopArticleVideoPlayer.tsx, src/jwplayer/players/MobileArticleVideoPlayer/MobileArticleVideoPlayer.tsx, src/jwplayer/players/MobileArticleVideoPlayer/OffScreenOverlay/OffScreenOverlay.tsx
* Added class names to the mobile player elements to fix ToC overlap issue
* The code in UCP responsible for shifting the ToC based on certain class names is found in the following two places:
* https://github.com/Wikia/unified-platform/blob/bb5a7385fd77c1da778a45e24480848bc35f56f0/skins/FandomMobile/scripts/TableOfContents.ts#L35
* https://github.com/Wikia/unified-platform/blob/bb5a7385fd77c1da778a45e24480848bc35f56f0/skins/FandomMobile/scripts/TableOfContents.ts#L64
* There is still a small issue with the ToC element overlapping the right side of the bottom title bar, but this PR addresses the main issue of the ToC overlapping the close button
* Added classnames on certain video player elements, so that regression tests can target them easily
=> DPAD-1030 :: Added class names to the mobile player elements to fix ToC overlap issue

package.json, src/jwplayer/players/MobileArticleVideoPlayer/MobileArticleVideoPlayer.tsx, src/jwplayer/players/MobileArticleVideoPlayer/OffScreenOverlay/OffScreenOverlay.tsx, src/jwplayer/players/shared/CloseButton.tsx, src/jwplayer/players/shared/JWEvents.ts, src/utils/useAdBreak.ts, test-jw/src/App.js, test-jw/src/app.css
* The close button needs to be moved down, below the Learn More overlay, whenever an ad plays
* Added in a react hook to check whether the player is in an ad or not
* The close button is moved down by a static amount of 40px. Grabbing the Learn More button element is slightly difficult, given that the element exists inside of an iFrame that's sourced from a different domain
=> DPAD-1068 :: Move Close button down on Mobile Ad

src/jwplayer/players/shared/JwPlayerWrapper.tsx, src/jwplayer/players/shared/addBaseTrackingEvents.ts, src/jwplayer/utils/videoTracking.ts
In order to enable the engineering team to view real-time and historical metrics for some of the key stats, let's use our metric library, which sends our video events to the DW special tracking table in a sampled fashion (20% of events). Even though this does increase the number of events were are sending (although a much smaller subset) our queries should be much less expensive. 
Events:
* Player loaded
* Player ready
* Paused
* Played
* Ad started
* Ad completed
=> DPAD | Add video metrics

package.json
Ditch the beta postfix for the package version; Start fresh with a fresh 2.0.0, since the new player has been released to 100% of wikis now
=> Publish non beta version of the new video player

package.json, src/jwplayer/players/DesktopArticleVideoPlayer/DesktopArticleVideoPlayer.tsx
* https://fandom.atlassian.net/browse/DPAD-1175
=> DPAD-1175: Fix desktop mini-player viewability 

package.json, src/jwplayer/players/DesktopArticleVideoPlayer/DesktopArticleVideoPlayer.tsx, src/jwplayer/players/MobileArticleVideoPlayer/MobileArticleVideoPlayer.tsx, src/jwplayer/players/shared/JwPlayerWrapper.tsx, src/jwplayer/players/shared/LoadableVideoPlayerWrapper.tsx, src/jwplayer/types.d.ts, test-jw/src/App.js
[DPAD-1213](https://fandom.atlassian.net/browse/DPAD-1213)
JW has a built-in option to prevent auto-starting until the player is in “view” (“viewable” from an advertiser perspective, >50% of pixels). However, this setting only affects the initial play. If “related” plays continue afterward, they will start regardless of the player’s visibility.
This PR addresses this issue by counting the number of videos that has been watched and then stopping the player if its not on screen (at least 50% on the screen according to JW).
Simply because that index changes when another playlist is selected (be it manually or automatically), so its not reliable enough to be used to count watched videos.
[sandbox-s7](https://paweltest2.sandbox-s7.fandom.com/wiki/Test-video)
=> DPAD-1213 :: Stop auto-advancement if the player is not viewable

package.json, src/jwplayer/players/CanonicalVideoPlayer/CanonicalVideoPlayer.tsx
Use the spread operator on the AdEng config payload object instead of passing in the whole object - it should be passed in as { ...payload } not { payload }
=> DPAD-1337 :: Fix Canonical Video Player AdEng configs

src/jwplayer/players/RedVentureVideoPlayer/RedVentureVideoPlayer.tsx, src/jwplayer/players/RedVentureVideoPlayer/redVenturePlayerOnReady.ts, src/jwplayer/utils/useAdComplete.ts
- Added in a jwPlayerKey incrementor, for cases where there are multiple RedVenture video players on sites such as gamespot's seemless article pages
- Added in multiple debug log statements around AdEng calls for easier debugging during the dev cycle; comments/TODOs have been added to remove those before deploying to Prod, if necessary.
=> DPAD-1371 :: Add in AdEng support to the RedVenture (PlayerOne) Video Players

src/jwplayer/players/RedVentureVideoPlayer/RedVentureVideoPlayer.tsx, src/jwplayer/types.d.ts, src/stand-alone/loaderHelper.ts, src/stand-alone/standalone-loader.tsx
- Added in support for Signed urls for the JW Player
- Added in the jwtSignedContentAuth param to the standalone-loader.tsx, which is appended to the /v2/media API call. This is only useful if the workspace in which the mediaId (or/and the player as depending on content protection setup in the JW Dashboard) is located in, is protected by Signed Urls
- Added in a playerUrl param to the standalone-loader.tsx, which passes down the playerUrl to the RedVentureVideoPlayer.tsx, and eventually passes in the playerUrl to the already JwPlayerWrapper component (which has already existed). This param was added in to allow the application that instantiates this player to decide what player should be used, and can only be used to add in a Signed Url for the player (as per the JW Dashboard setup of the …
=> DPAD-1440 :: Allow Signed Content to work with the RedVenture video player

src/jwplayer/players/RedVentureVideoPlayer/RedVentureVideoPlayer.tsx
Check if window.Phoenix.hasAds is an actual function and if it can be called; on GameFAQs the key of hasAds is defined on the window.Phoenix object but is actually undefined for some reason, this should not prevent the player from instantiating on the page and crashing
=> DPAD-1490 :: Check if window.Phoenix.hasAds is an actual function

package.json, src/jwplayer/players/RedVentureVideoPlayer/RedVentureVideoPlayer.tsx, stand-alone/package.json
Switch out the hasAds functionality with the !window.Phoenix.User.isPremium() check, so that this check is more specific to GiantBomb (GB)
=> DPAD-1494 :: Switch out the hasAds functionality 

stand-alone/deploy/purge/nodes.ts
We really shouldn't bother with dev-wk-cdn -- this application's traffic never uses those nodes
=> Revised CDN node list

src/jwplayer/players/DesktopArticleVideoPlayer/DesktopArticleVideoPlayer.tsx, src/jwplayer/players/MobileArticleVideoPlayer/MobileArticleVideoPlayer.tsx, src/jwplayer/players/MobileArticleVideoPlayer/OffScreenOverlay/videoDetails.module.scss, src/jwplayer/players/MobileArticleVideoPlayer/mobileArticleVideoPlayer.module.scss
https://fandom.atlassian.net/browse/FCPPT-103
Deployed: https://starwars.sandbox-xw1.fandom.com/wiki/Yoda
Description (extended from ticket description):
- The timing for showing placeholder was changes, we look now for readiness of player not `adComplete` particularly because this variable name is misleading - it triggers right after receiving jwplayer setup but jwplayer is still not rendered so placeholder should be still there in this case.
- Video details were shown before even loading video player which is why it also should wait for video player.
- Shadow was moved to the video details to not blend with fandom page.
<details>
<summary>After (sandbox on the left) vs. before (production on the right)</summary>
https://github.com/Wikia/jwplayer-fandom/assets/25872895/f733b496-9b71-4cd8- …
=> FCPPT-103: Fix jwplayer placeholder issues

src/jwplayer/utils/formatTime.ts
[Ticket](https://fandom.atlassian.net/browse/COTECH-683)
I noticed that for some videos (for example first video on the Yoda page) instead of the video duration there is `NaN:NaN` displayed. Currently, there is an if statement that checks if property `duration` is less or equal to zero but it doesn't take into account situations when duration is missing (it's the case for Yoda's video).
Also, it's better to move this statement as a first instruction in the function - we don't want to compute anything if the duration is not a number.
cc @Wikia/site-experience @Wikia/cotech
=> COTECH-683 (fix): handle missing duration property

package.json, src/contexts/MobileArticleVideoContext.ts, src/jwplayer/players/MobileArticleVideoPlayer/MobileArticleVideoPlayer.tsx, src/jwplayer/types.d.ts, src/loaders/MobileArticleVideoLoader.tsx, src/loaders/types.d.ts, src/vimeo/players/VimeoMobileArticleVideoPlayer.tsx, src/youtube/players/YoutubeMobileArticleVideoPlayer.tsx
* Added new prop for `MobileArticleVideoLoader`: `scrollTopPosition` - a string that is passed as `top` position for the container in scroll mode
* Passed through MobileArticleVideoContext to avoid unnecessary prop passing down 
* Removed unused props `hasPartnerSlot` and `isFullScreen` and commented out tracking code
=> COTECH-136 (step2) | configurable mobile scroll position

src/jwplayer/players/shared/JwPlayerWrapper.tsx, src/jwplayer/players/shared/JwPlayerWrapperWithStrategyRules.tsx, src/jwplayer/players/shared/addBaseTrackingEvents.ts, src/jwplayer/utils/videoTimingEvents.ts, src/jwplayer/utils/videoTracking.ts
1. Different `ga_category` values for JWP with the strategy rules to make it easier and faster query for the results and splitting them by legacy JWP and JWP with the strategy rules.
2. Clean up of some legacy HTTP tracking request we don't need.
=> COTECH-1026 Two changes after QA phase

src/jwplayer/players/shared/JwPlayerWrapper.tsx
It's an attempt to address COTECH-1225. While I’m not certain this will completely resolve the issue, it should help to pinpoint the problem, as the current implementation causes errors. Additionally, we need to create a separate ticket to remove Wirewax entirely.
=> COTECH-1225 Drop support for Wirewax

scripts/jwp-imports-create.js, scripts/jwp-imports-update.js
This script was used to add the `fandom:thumbnail` custom parameter to every Medal import on the JW platform.
Versioning it to allow future use for batch updating other imports as needed.
=> COTECH-1849 Add script to update Medal imports with custom param fandom:thumbnail

scripts/jwp-imports-create.js, scripts/jwp-media-refresh.js
This PR introduces a new script that automates the process of updating media in JWPlayer based on refreshed content from the Medal API. The script performs the following actions:
- Retrieves dynamic playlists from JWPlayer.
- Extracts relevant tags from each playlist to filter media.
- Uses the collected tags to fetch media from JWPlayer.
- Sends a list of content IDs (extracted from the media) to Medal API to retrieve updated media data.
- Updates the JWPlayer media metadata (including the thumbnail, publish start/end dates) and triggers a reupload with the new video URL.
Additionally, the script supports a dry-run mode. When enabled, the script logs the intended updates without making actual changes, allowing for safe testing.
This solution aims to streamline the synchronization process …
=> COTECH-1876 Add script to refresh Medal content imported to JWP
